spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false
    username: root
    password: MySQL@root_2022#pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


  jpa:
    database: MySQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          batch_size: 10
          order_inserts: true


url.default: /api

configparse:
    useragent: FlySearchBot/1.0
    referrer: http://www.google.com
    timeout: 10000

configsites:
  sites:
    - url: https://www.svetlovka.ru
      name: Светловка
    - url: https://dombulgakova.ru
      name: Булгаковский Дом
    - url: https://www.playback.ru
      name: PlayBack.ru
