spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    username: root
    password: testBase
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          batch_size: 10
          order_inserts: true

  security:
    user:
      name: user
      password: user
      roles: user




configparse:
    useragent: FlySearchBot/1.0
    referrer: http://www.google.com
    timeout: 10000

url.default: /api

configsites:
  sites:
    - url: https://www.svetlovka.ru
      name: Светловка
    - url: https://dombulgakova.ru
      name: Булгаковский Дом
    - url: https://dimonvideo.ru
      name: DimonVideo

